/globalpars/seed 12340001 # change the seed for multiple runs to 0002, 0003 etc.

#NB, chosen seed and shift module allow the range between 
#fSeed=12340001 and 12341000
#e.g, 1000 files (with 10^4 events that's a total of 10^7 events)

/primary/gammaEnergy 511 keV
# names of files
/globalpars/ISensorDataFileName pet_data_bgo_heart_w32_ 
/globalpars/GlobalDataFileName global_data_bgo_heart_w32_ 
/globalpars/HistogramsFileName control_histograms_bgo_w32_ 