/globalpars/seed 12340001 # change the seed for multiple runs to 0002, 0003 etc.

# To write only integrated data (no time info in sensors)
/globalpars/idataonly false

# To generate optical photons or not
/globalpars/generateOpticalPhotons true

# names of files
/globalpars/SensorDataFileName sensor_data_test_ 
/globalpars/ISensorDataFileName isensor_data_test_ 
/globalpars/GammaInteractionsFileName gamma_interactions_test_
/globalpars/HistogramsFileName control_histograms_test_ 