# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Defube seed in init_globals
#/globals/seed 12340001 # change the seed for multiple runs to 0002, 0003 etc.

# Will run the default, e.g, 8 threads. 
/run/numberOfThreads 8

#
# Set some default verbose
/control/verbose 1
/control/saveHistory
/run/verbose 1
/event/verbose 0
/tracking/verbose 0


# Detector construction

/detector/crystalMaterial CsI
/detector/crystalWidth 48 mm
/detector/crystalX0Length 2
/detector/teflonThickness 0.08 mm
/detector/teflonCoatings 5
/detector/sipmXY 6 mm
/detector/sipmZ 1 mm
/detector/epoxyZ 0.15 mm
/detector/sipmActiveXY 5.9 mm
/detector/sipmActiveZ 0.01 mm


/primary/timeBinning 200 ns
/primary/gammaEnergy 511 keV

# Initialize kernel
/run/initialize

# number of events to generate
/run/beamOn 10000
